### ISSUE TITLE
throttle should define the behavior of the first element

### ISSUE THREAD

**Issue by inamiy** [apple/swift-async-algorithms#113]
I find there are significant flaws in current `throttle` implementation.

1. First value is not emitted
2. Value is not emitted at throttled-interval-end when `latest = true`

### 1. First value is not emitted

From test code:

```swift
  func test_rate_3() {
    validate {
      "abcdefghijk|"
      $0.inputs[0].throttle(for: .steps(3), clock: $0.clock)
      "--c--f--i--|"
    }
  }
```

AFAIK, this `throttle` behavior is not compatible with any existing Rx frameworks, e.g. Combine, RxSwift, ReactiveSwift.

The correct result should (at least) be:

```swift
  func test_rate_3() {
    validate {
      "abcdefghijk|"
      $0.inputs[0].throttle(for: .steps(3), clock: $0.clock)
      "a--d--g--j-|"
    }
  }
```

where first `a` is emitted correctly, then start throttling for intervals.

### 2. Value is not emitted at throttled-interval-end when `latest = true`

From existing framework's behavior, `latest = true` normally means the latest cached value will be emitted at "throttled-interval-end".

For example:

```swift
    func test() async throws {
        let now = ContinuousClock.now

        let countUpStream = AsyncTimerSequence(interval: .seconds(1), clock: .continuous)
            .map { now.duration(to: $0).components.seconds } // 1, 2, 3, ...

        let throttledStream = countUpStream.throttle(for: .seconds(2.1), latest: true)

        let task = Task {
            for try await value in countUpStream {
                print("===> count", value)
            }
        }

        for try await value in throttledStream {
            print("===> throttled", value)
        }

        _ = await task.result

        print("===> done")
    }
```

This test runs timer starting from `1 sec`, and throttling interval is `2.1 sec`.

When `latest = true`, the ideal result should print:

```
// Ideal result
===> count 1
===> count 2
===> throttled 2 // at 2.1 sec
===> count 3
===> count 4
===> throttled 4 // at 4.2 sec
===> count 5
===> count 6
===> throttled 6 // at 6.3 sec
===> count 7
===> count 8
===> throttled 8 // at 8.4 sec
```

But current impl results:

```
// Current result
===> count 1
===> count 2
===> count 3
===> throttled 3 // at 3 sec
===> count 4
===> count 5
===> count 6
===> throttled 6 // at 6 sec
===> count 7
===> count 8
===> count 9
===> throttled 9 // at 9 sec
```

**Comment by inamiy** [comment]
EDIT: For ideal result:

```diff
 ...
 ===> throttled 2 // at 2.1 sec (by latest = true)
 ===> count 3
+===> throttled 3 // at 3 sec
 ===> count 4
 ===> count 5
+===> throttled 5 // at 3 + 2.1 sec (by latest = true)
```

may be more accurate result because `===> throttled 3` won't be the target of throttling.

**Comment by phausler** [comment]
I think the crux here is that the first element was undefined in the relationship to the throttled rate. We can safely define that as not exceeding the rate in all cases.
