### ISSUE TITLE
`zip` is not Rx compatible (take 2)

### ISSUE THREAD

**Issue by inamiy** [apple/swift-async-algorithms#117]
Retry of:
- #116

```swift
func test() async throws {
    let initial = ContinuousClock.now

    let countUpStream = AsyncTimerSequence(interval: .seconds(1), clock: .continuous)
        .map { initial.duration(to: $0).components.seconds }
    let countUpStream2 = AsyncTimerSequence(interval: .seconds(3), clock: .continuous)
        .map { initial.duration(to: $0).components.seconds }

    let zipped = zip(countUpStream, countUpStream2)

    for try await value in zipped {
        let currentSec = initial.duration(to: .now).components.seconds
        print("===> zip: at \(currentSec) sec, \(value)")
    }
}
```

Result:

```
===> zip: at 3 sec, (1, 3)
===> zip: at 6 sec, (3, 6)
===> zip: at 9 sec, (6, 9)
===> zip: at 12 sec, (9, 12)
===> zip: at 15 sec, (12, 15)
...
```

To Be:

```
===> zip: at 3 sec, (1, 3)
===> zip: at 6 sec, (2, 6)
===> zip: at 9 sec, (3, 9)
===> zip: at 12 sec, (4, 12)
===> zip: at 15 sec, (5, 15)
...
```

```
--1-2-3-4-5-6-7-8-9-->
------3-----6-----9-->

zip
----(1,3)--(2,6)--(3,9)--->
```

**Comment by DevAndArtist** [comment]
I'd like to run this test but I'm failing to make this test generate anything, for some reason on my machine it stalls the while test. I'm using the latest trunk toolchain. 🤔

**Comment by inamiy** [comment]
@DevAndArtist 
This test is using `swift-5.6` branch and tested with Xcode 13.3.

**Comment by DevAndArtist** [comment]
Unfortunately I cannot run the test for some reason. I only managed to run it by using the Mac (Rosetta) scheme, but the output there is even weirder:

```
===> zip: at 0 sec, (0, 0)
===> zip: at 0 sec, (0, 0)
===> zip: at 0 sec, (0, 0)
===> zip: at 1 sec, (0, 1)
===> zip: at 4 sec, (1, 4)
===> zip: at 7 sec, (4, 7)
===> zip: at 10 sec, (7, 10)
===> zip: at 13 sec, (10, 13)
===> zip: at 16 sec, (13, 16)
```

**Comment by phausler** [comment]
awaiting the second element in the tuple ends up delaying the iteration of the next first element of the tuple so the back pressure is causing the shift you are seeing (which is somewhat expected). To note: this project does not have any goal to be Rx compliant - granted it shares a lot of inspiration to similar systems. The differential is that the back pressure is distinctly modeled always as a back pressure of 1 (awaiting the call to next).

**Comment by DevAndArtist** [comment]
Ah right so a general marble diagram wouldn't apply here.

This is what happening:

```swift
A:--1-(await B)--3--(await B)--->
B:--------------3-----6-----9-->

zip
----(1,3)--(3,6)--(6,9)--->
```

**Comment by inamiy** [comment]
Ah, I see!
So the async-pull nature of `AsyncSequence` will mutually interfere the timing of both emission.

When I changed the example code to not emit the time (which again makes the whole example difficult) 
but incrementing count, it worked as expected:

```swift
    func test() async throws {
        let initial = ContinuousClock.now
        var count1 = 0
        var count2 = 0

        let countUpStream = AsyncTimerSequence(interval: .seconds(1), clock: .continuous)
            .map { _ -> Int in count1 += 1; return count1 }
        let countUpStream2 = AsyncTimerSequence(interval: .seconds(3), clock: .continuous)
            .map { _ -> Int in count2 += 1; return count2 }

        let zipped = zip(countUpStream, countUpStream2)

        for try await value in zipped {
            let currentSec = initial.duration(to: .now).components.seconds
            print("===> zip: at \(currentSec) sec, \(value)")
        }
    }
```

```
===> zip: at 3 sec, (1, 1)
===> zip: at 6 sec, (2, 2)
===> zip: at 9 sec, (3, 3)
===> zip: at 12 sec, (4, 4)
===> zip: at 15 sec, (5, 5)
```

So I confirmed that this is an expected behavior, and also follows the normal use case of `zip`
(except one needs to take special care of the timed value with async-pull when using `AsyncTimerSequence`).
