### ISSUE TITLE
Deadlock in Task.select when using clock's sleep 

### ISSUE THREAD

**Issue by mbrandonw** [apple/swift-async-algorithms#139]
I'm using Swift dev snapshot 2022-03-02 with Xcode 13.3.

By making a small tweak to [one](https://github.com/apple/swift-async-algorithms/blob/18749897a885e596d37efc1c4c911b4581d5b3cb/Tests/AsyncAlgorithmsTests/TestTaskSelect.swift#L17-L25) of the `Task.select` tests I am able to produce a deadlock:

```diff
 let firstValue = await Task.select(Task {
+  try! await Task.sleep(until: .now + .seconds(1), clock: .continuous)
   return 1
 }, Task {
   try! await Task.sleep(until: .now + .seconds(2), clock: .continuous)
   return 2
 }).value
```

It's worth noting that it does not deadlock if you use `Task.sleep` without a clock:

```swift
let firstValue = await Task.select(Task {
  try! await Task.sleep(nanoseconds: NSEC_PER_SEC)
  return 1
}, Task {
  try! await Task.sleep(nanoseconds: 2*NSEC_PER_SEC)
  return 2
}).value
```

Is there something about clocks and sleeping that is causing this? I see the same behavior with suspending clocks too.

**Comment by kielgillard** [comment]
Is this PR related to this issue? https://github.com/apple/swift/pull/42527

**Comment by mbrandonw** [comment]
@kielgillard, nice find! When I now run the test with the 2022-04-23 toolchain it no longer deadlocks, but the test does fail non-deterministically.

Also, regardless of the test passing or failing, it does so immediately (0.002 seconds runtime), and so clearly the continuous clock is not actually waiting for time to pass, which would explain the non-determinism:

```
Test Suite 'Selected tests' passed at 2022-04-25 08:23:12.181.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.003) seconds
```

On the other hand, the suspending clock is working exactly as I expect. The test passes 100% of the time (I just performed a repeating test with 100 iterations) and the test actually takes a second to execute:

```
Test Suite 'Selected tests' passed at 2022-04-25 08:24:20.392.
	 Executed 1 test, with 0 failures (0 unexpected) in 1.034 (1.040) seconds
```

@phausler Is there anything about `ContinuousClock` that would cause this behavior?

**Comment by phausler** [comment]
yea the deadlock was not a deadlock but instead a stall out on certain time base calculations so yes it was related. 

for the intermittent failure; can you post that code in whole? the code paths for those are VERY similar.

**Comment by mbrandonw** [comment]
This test fails non-deterministically with the 2022-04-23 snapshot:

```swift
  func test_first() async {
    let firstValue = await Task.select(Task {
      try! await Task.sleep(until: .now + .seconds(1), clock: .continuous)
      return 1
    }, Task {
      try! await Task.sleep(until: .now + .seconds(2), clock: .continuous)
      return 2
    }).value
    XCTAssertEqual(firstValue, 1)
  }
```

If I run the test in isolation it fails a lot less frequently than it passes, but still does fail eventually. The easiest way to nearly force a failure is to run this test as part of the larger AsyncAlgorithms test suite, or if you use Xcode's repeated test run feature.

The strangest thing about this test is that it executes immediately:

```swift
Executed 1 test, with 0 failures (0 unexpected) in 0.001 (0.003) seconds
```

So clearly the clock is not sleeping for 1 second.

**Comment by mbrandonw** [comment]
> I think that might be related to this issue: [apple/swift#58396](https://github.com/apple/swift/pull/58396)

Hey @phausler, I can now confirm that with the newest snapshot (20220504) the test passes as I expect with the continuous and suspended clocks. So will close this issue out!

BTW, would it be accepted for me to submit a PR that updates some `Task.select` tests to exercise this behavior?
