### ISSUE TITLE
More detailed testing needs to be done tracking the transitions for AsyncChannel

### ISSUE THREAD

**Issue by phausler** [apple/swift-async-algorithms#148]
The changes associated with https://github.com/apple/swift-async-algorithms/commit/047ab6abef71bdb6758c7bed661a04c04f5b056a need to have some sort of test that triggers that previous behavior to prove that the change listed definitely does what we think it does (which I am pretty sure it is correct). Having tests to prove its correctness will aide in preventing possible regressions etc.

**Comment by twittemb** [comment]
Just for the record: both `AsyncChannel` and `AsyncThrowingChannel` should have those tests.

**Comment by FranzBusch** [comment]
We can close this issue since we have re-implemted the AsyncChannel and added tests.
