### ISSUE TITLE
[Question `AsyncThrowingSequence`] Should failure resume and fail all producers/consumers

### ISSUE THREAD

**Issue by twittemb** [apple/swift-async-algorithms#155]
Hi,

We’ve recently merged a PR https://github.com/apple/swift-async-algorithms/pull/152 where the finish operation instantly resumes all the pending producers and consumers (with a nil value), thus ending all the iterators.

I was wondering if we should have the same behaviour for failures. As it is a terminal event, we have the same kind of risk for infinite suspensions. I guess when sending a failure, all the pending operations should resume instantly. All the awaiting consumers should receive the failure and the future iterations should also resume instantly.

@phausler what do you think ?

The `fail(_:)` function would also be  not async. It makes sense since, as a terminal event, no back pressure should be applied.

**Comment by phausler** [comment]
the logic here is sound. The behavior we would ideally want for multiple consumers is that if a fail is sent, it needs to definitely be consumed; that is a long way of saying - I need to ruminate on this one a bit.

**Comment by phausler** [comment]
so after thinking about the situations for this: provided it can be accomplished w/o starving either side (which I think I have convinced myself that is accomplishable as you outlined). From a symmetry standpoint it feels right to have back pressure be the same for finish and fail. In short that sounds like a good change to make.

**Comment by twittemb** [comment]
Thanks for your analysis. I’ll work on that as soon as I can. I will keep the issue open until the PR is done so we can make the link between the issue and the PR.

**Comment by twittemb** [comment]
https://github.com/apple/swift-async-algorithms/pull/164
