### ISSUE TITLE
[Help needed] Unable to use the Package in Xcode project

### ISSUE THREAD

**Issue by manuelCarlos** [apple/swift-async-algorithms#160]
Hi! 

I tried using the package on a personal project but because the public API is annotated
with  `@available(macOS 9999, iOS 9999, tvOS 9999, watchOS 9999, *)`  
 the compiler doesn't build my project.
 
 So I tried:
   - Using the latest Swift development toolchain in Xcode 13.4 and in Xcode 14 Beta
   - Passed `-Xfrontend -disable-availability-checking` to the compiler in the project build settings
   
But In the end neither of these made the errors go.

Is there some other way to work around the iOS availability error?
Thanks 🙏

**Comment by phausler** [comment]
This is a configuration and availability issue; https://github.com/apple/swift-async-algorithms/pull/165 will be targeting some of those issues and should (once that is completed) resolve those.

**Comment by manuelCarlos** [comment]
Wow that's great. Thank you!

**Comment by phausler** [comment]
@manuelCarlos It would be helpful to make sure ive got everything lined up right to have folks test that PR (since CI does not yet have the right toolchains). Hand-testing all of the potential configurations is not trivial so any assistance to validate things would be much appreciated.

**Comment by manuelCarlos** [comment]
@phausler 
My project use case is quite simple - I only need to throttle  an AsyncStream - so  I just  tried using `throttle(for:latest:)` with your PR and this time it built correctly. ✅
Looks goods now!
