### ISSUE TITLE
Crash upon a second send on a channel

### ISSUE THREAD

**Issue by DavidKmn** [apple/swift-async-algorithms#175]
I am using an AsyncChannel between two tasks, one task is sending events and the second task is running a for await loop where events are processed. Upon sending the second event I am getting this crash..
![Screenshot 2022-06-28 at 19 43 47](https://user-images.githubusercontent.com/35953014/176258714-5546d511-3593-4506-b0e9-51f045cd9e87.png)

**Comment by twittemb** [comment]
Hi @DavidKmn 

could you share the code that induce that crash please?

**Comment by DavidKmn** [comment]
All solved, there was an issue with the channel being continuously recreated due to the mismanagement of the lifecycle of the channel when using in conjunction with of the SwiftUI.
