### ISSUE TITLE
Warnings when flag `-warn-concurrency` is enabled for `AsyncAlgorithms`

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-async-algorithms#196]
If I add `warn-concurrency` and `enable-actor-data-race-check` as `swiftSettings` for `AsyncAlgorithms` target I get some warnings. This is on macOS Ventura (13.0 Beta (22A5331f)) and using Xcode 14.0 beta 5 (14A5294e). 

```
  .unsafeFlags([
           "-Xfrontend", "-warn-concurrency",
           "-Xfrontend", "-enable-actor-data-race-checks",
     ])
```

<img width="1624" alt="Screenshot 2022-09-10 at 22 42 53" src="https://user-images.githubusercontent.com/864410/189501212-10c8629b-a246-4c2f-83f5-f79be70d9ae4.png">

It feels like such a serious and great project like this ought to lead the way in terms of correctness of structured concurrency, so I expect:
1. These flags to be enabled
2. Packages, or at least the public one `AsyncAlgorithms` to not have any concurrency warnings.

**Comment by FranzBusch** [comment]
Thanks for opening this! I agree that we should fix all the warnings. I opened a PR that changes the `debounce` implementation which also fixes the `debounce` specific warnings: https://github.com/apple/swift-async-algorithms/pull/198

**Comment by phausler** [comment]
we kinda need a way to add these flags without requiring them for normal builds (since iirc that poses issues to other libraries linking swift packages)

**Comment by FranzBusch** [comment]
I am going to close this issue because we enabled the flags and are warning free in the main package. However, we are not warning free in the validation tests which we have to tackle separately.

**Comment by Sajjon** [comment]
Thanks for the update!
