### ISSUE TITLE
Removed `Task.select(_:)` method is still called.

### ISSUE THREAD

**Issue by Malauch** [apple/swift-async-algorithms#225]
Package stoped building in my projects recently. Xcode highlights this line as a culprit:
https://github.com/apple/swift-async-algorithms/blob/db847ef41037d9b279cb51c6e167e5cb3f4abfdc/Sources/AsyncAlgorithms/AsyncCombineLatest2Sequence.swift#L236
<img width="950" alt="Zrzut ekranu 2022-10-27 o 12 24 32" src="https://user-images.githubusercontent.com/13001524/198260514-fa0ddf8c-5a7e-4190-a3e0-95db80e011b1.png">

That line still uses Task.select(_:) method which was removed in #217 commit.

**Comment by FranzBusch** [comment]
I am currently already working on providing a `combineLatest` implementation that is not using the removed `Task.select`.

**Comment by JessyCatterwaul** [comment]
Why is it permitted to commit to `main` in a non-compiling state? Does this project need another official branch?

**Comment by twittemb** [comment]
@FranzBusch i guess we can close this ?
