### ISSUE TITLE
Debounce does not yield values if rate is higher than the pace of the stream

### ISSUE THREAD

**Issue by pixelrevision** [apple/swift-async-algorithms#260]
Version: 0.1.0

This may be a misunderstanding of how debounce is supposed to work with async streams but it appears that if the value of the interval is higher than the rate that the steam yields values it waits for the entire sequence to finish before a value is yielded.

In the case below `testDebounceIntervalGreaterThanRate` predictably only yields when the stream is complete always resulting in collect being `[9]`.

```swift
func testDebounceIntervalGreaterThanRate() async {
  var collect = [Int]()
  for await value in values(10, .milliseconds(100)).debounce(for: .milliseconds(200)) {
    collect.append(value)
  }
  XCTAssert(collect.count > 1, "\(collect) should have more than one value present")
}

func values(_ count: Int, _ duration: Duration) -> AsyncStream<Int> {
  AsyncStream { continuation in
    Task {
      for i in 0..<count {
        continuation.yield(i)
        try? await Task.sleep(for: duration)
      }
      continuation.finish()
    }
  }
}
```

The following work as expected (with maybe slight variance due to the sleep duration):
```swift
func testDebounceIntervalEqualToRate() async {
  var collect = [Int]()
  for await value in values(10, .milliseconds(200)).debounce(for: .milliseconds(200)) {
    collect.append(value)
  }
  XCTAssert(collect.count >= 5, "\(collect) should have at least 5 values present")
}

func testDebounceIntervalLessThanRate() async {
  var collect = [Int]()
  for await value in values(10, .milliseconds(200)).debounce(for: .milliseconds(100)) {
    collect.append(value)
  }
  XCTAssert(collect.count == 10, "\(collect) should have all values present")
}
```

**Comment by FranzBusch** [comment]
This is expected unless I am missing something. Debounce is waiting for at least the interval you passed it until it produces a value. In your first example, you are producing a value every 100ms but are debouncing for 200ms. That means every 100ms a new value is produced which will reset the 200ms timer so only the last element is returned from the debounced sequence.

**Comment by FranzBusch** [comment]
I am going to close this issue since it looks like this is working as expected. Please feel free to re-open it if you still think that `debounce` isn't doing the right thing.
