### ISSUE TITLE
`AsyncChunksOfCountSequence` does not create chunks of 1 element each.

### ISSUE THREAD

**Issue by knovichikhin** [apple/swift-async-algorithms#268]
`AsyncChunksOfCountSequence` does not create chunks of 1 element each. Instead it creates 1 chunk of all elements.

```
for await chunk in ["1", "2", "3"].async.chunks(ofCount: 1) {
    print(chunk)
}
```

Output:

```
["1", "2", "3"]
```

Likely due to this line not checking that `result.count == count`: https://github.com/apple/swift-async-algorithms/blob/b3394663fd8ad9c701cbfcffcaedb64afc7e92be/Sources/AsyncAlgorithms/AsyncChunksOfCountSequence.swift#L55

**Comment by FranzBusch** [comment]
This PR should fix it: https://github.com/apple/swift-async-algorithms/pull/293
