### ISSUE TITLE
How do I cancel async task when using AsyncChannel

### ISSUE THREAD

**Issue by Vincent-liuwingsang** [apple/swift-async-algorithms#283]
Hi, swift newbie here but I'm trying to implement a serial queue that supports async task.
"""
typealias AsyncClosure = () async -> Void
let channel = AsyncChannel<AsyncClosure>()
func start() async {
    for await task in channel {
        await task() // How do I process the next task in channel if current task takes more than 10 seconds?
    }
}
"""

**Comment by FranzBusch** [comment]
Sorry for the late reply but what you can do is this

```
for await task in channel {
    await withTaskGroup(of: Void.self) { group in
        group.addTask {
            await task()
        }
        group.addTask {
            try? await Task.sleep(for: .seconds(10))
        }

        await group.next()
        group.cancelAll()
}
```
