### ISSUE TITLE
Release request for 1.0.1

### ISSUE THREAD

**Issue by kateinoigakukun** [apple/swift-async-algorithms#314]
We started using swift-async-algorithm in ci.swift.org to build Swift SDK generator now. (https://github.com/apple/swift/pull/72728)
However, we currently use [`main` branch instead of a tagged revision](https://github.com/apple/swift/pull/72728#discussion_r1612694689) to checkout a revision including https://github.com/apple/swift-async-algorithms/commit/6ae9a051f76b81cc668305ceed5b0e0a7fd93d20 fix.
This is not ideal situation for the build stability, so could you publish 1.0.1 of swift-async-algorithm including https://github.com/apple/swift-async-algorithms/commit/6ae9a051f76b81cc668305ceed5b0e0a7fd93d20?

Thanks in advance :pray:

**Comment by MaxDesiatov** [comment]
cc @FranzBusch @phausler

**Comment by MaxDesiatov** [comment]
It has been tagged now: https://github.com/apple/swift-async-algorithms/releases/tag/1.0.1
