### ISSUE TITLE
New tagged release request

### ISSUE THREAD

**Issue by Brett-Best** [apple/swift-async-algorithms#339]
Hello, it would be great if a new tagged release could be published that includes https://github.com/apple/swift-async-algorithms/commit/4c3ea81f81f0a25d0470188459c6d4bf20cf2f97. Thanks!

**Comment by xtremekforever** [comment]
+1, this is something that should probably be part of a small bugfix release at least!

**Comment by phausler** [comment]
done

**Comment by phausler** [comment]
tagged as 1.0.3
