### ISSUE TITLE
Performance tests for merge only measure one active side

### ISSUE THREAD

**Issue by phausler** [apple/swift-async-algorithms#45]
The test currently measures the performance of merge as such:

```
  func test_merge2() async {
    await measureSequenceThroughput(output: 1) {
      merge($0, (0..<10).async)
    }
  }
```

Ideally we should measure cases where we have two inputs continuously emitting values. This likely needs a second emitter being added into `measureSequenceThroughput` so that it can be used for zip and other such combination APIs.

**Comment by kingreza** [comment]
I think we can close this one out.
