### ISSUE TITLE
AsyncChannel naming is provisional and needs review

### ISSUE THREAD

**Issue by phausler** [apple/swift-async-algorithms#47]
The naming of `AsyncChannel` was introduced as a placeholder name. It deserves more consideration to existing paradigms, the current name is inspired from  [`Channel`](http://cml.cs.uchicago.edu/pages/cml.html#SIG:CML.channel:VAL). This type needs a guide and some research/discussion on what a good name for this type should be.

**Comment by jmjauer** [comment]
I think the name `AsyncChannel` is well chosen - it is short and describes exactly the semantics.

**Comment by andersio** [comment]
Kotlin Coroutines names this [`RendezvousChannel`](https://atoulme.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental.channels/-rendezvous-channel/index.html). Though the "rendezvous" prefix is most likely a result of them also offering buffering variants and a special single-item coaleasing mode under the same `Channel` umbrella.

**Comment by twittemb** [comment]
Is there an official definition to what a `Channel` should be? especially regarding the synchronisation part between sender and receiver.

If the link @phausler has provided is considered an "official" definition, then I'm not sure we should keep the `Async` prefix. 

`Channel` alone would simply mean that we have implemented the official `Channel` paradigm with async/await as an implementation detail. Moreover `AsyncChannel` could be misleading by thinking `Async` means that sending a value is not bound to its consumption.

And the other hand, if the accepted definition of `Channel` does not imply the synchronisation between sender and receiver, then I guess `Channel` is a family of different implementations depending on the buffering policy (like Kotlin). If we want to go down that road then something like `RendezVousChannel` or similar could be interesting in comparison with a future `BufferedChannel` or so.

**Comment by paulofaria** [comment]
I think `Channel` and `BufferedChannel` works pretty well. I'm not sure the `Rendezvous` prefix buys us much. Also, since we're talking about `BufferedChannel` is there any work being done on that front? If not, I'm happy to contribute with an implementation/proposal.

**Comment by paulofaria** [comment]
Actually, this is (probably?) not possible to implement now, but it would be awesome if we could add deadlines to Channels like we did on [Venice](https://github.com/Zewo/Venice/blob/master/Tests/VeniceTests/Venice/ChannelTests.swift) (backed by [libdill](http://libdill.org/chsend.html)). Like the test excerpt below:

```swift
    func testDoubleSendTimeout() throws {
        let channel = try Channel<Int>()

        let coroutine1 = try Coroutine {
            XCTAssertThrowsError(
                try channel.send(111, deadline: 50.milliseconds.fromNow()),
                error: VeniceError.deadlineReached
            )
        }

        let coroutine2 = try Coroutine {
            XCTAssertThrowsError(
                try channel.send(222, deadline: 50.milliseconds.fromNow()),
                error: VeniceError.deadlineReached
            )
        }

        try Coroutine.wakeUp(100.milliseconds.fromNow())

        let coroutine3 = try Coroutine {
            try channel.send(333, deadline: .never)
        }

        XCTAssertEqual(try channel.receive(deadline: .never), 333)

        coroutine1.cancel()
        coroutine2.cancel()
        coroutine3.cancel()
    }
```

If not possible right now, what would we need in place to make it happen?

**Comment by paulofaria** [comment]
I moved the discussion above to its own [issue](https://github.com/apple/swift-async-algorithms/issues/168).

**Comment by eaigner** [comment]
I would just model it `1:1` like channels in Go, so as for the name `AsyncChannel` would be correct.

Why reinvent the wheel?

On a different note,  `close` seems like a more reasonable name for the `finish` method.

**Comment by FranzBusch** [comment]
IMO the current semantics fit very well with what we want to achieve with this type. The intention is to have a multi-producer multi-consumer root asynchronous sequence that allows lock-step programming between the involved parties. This is exactly what this type offers.

**Comment by FranzBusch** [comment]
@phausler I think we can close this issue now?

**Comment by phausler** [comment]
Yea, the name feels pretty solid and has been reviewed.
